// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: mediaplayer.proto

package mediaplayer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Control string  `protobuf:"bytes,1,opt,name=control,proto3" json:"control,omitempty"`
	Volume  float32 `protobuf:"fixed32,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Muted   bool    `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaplayer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_mediaplayer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_mediaplayer_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetControl() string {
	if x != nil {
		return x.Control
	}
	return ""
}

func (x *Request) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Request) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Control string  `protobuf:"bytes,1,opt,name=control,proto3" json:"control,omitempty"`
	Volume  float32 `protobuf:"fixed32,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Muted   bool    `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaplayer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_mediaplayer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_mediaplayer_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetControl() string {
	if x != nil {
		return x.Control
	}
	return ""
}

func (x *Response) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Response) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

var File_mediaplayer_proto protoreflect.FileDescriptor

var file_mediaplayer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x51, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75,
	0x74, 0x65, 0x64, 0x22, 0x52, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x32, 0x4f, 0x0a, 0x0b, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x67, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x64, 0x75, 0x62, 0x62, 0x38, 0x36, 0x2f, 0x68,
	0x61, 0x2d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mediaplayer_proto_rawDescOnce sync.Once
	file_mediaplayer_proto_rawDescData = file_mediaplayer_proto_rawDesc
)

func file_mediaplayer_proto_rawDescGZIP() []byte {
	file_mediaplayer_proto_rawDescOnce.Do(func() {
		file_mediaplayer_proto_rawDescData = protoimpl.X.CompressGZIP(file_mediaplayer_proto_rawDescData)
	})
	return file_mediaplayer_proto_rawDescData
}

var file_mediaplayer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mediaplayer_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: mediaplayer.Request
	(*Response)(nil), // 1: mediaplayer.Response
}
var file_mediaplayer_proto_depIdxs = []int32{
	0, // 0: mediaplayer.MediaPlayer.Communicate:input_type -> mediaplayer.Request
	1, // 1: mediaplayer.MediaPlayer.Communicate:output_type -> mediaplayer.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mediaplayer_proto_init() }
func file_mediaplayer_proto_init() {
	if File_mediaplayer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mediaplayer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaplayer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mediaplayer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediaplayer_proto_goTypes,
		DependencyIndexes: file_mediaplayer_proto_depIdxs,
		MessageInfos:      file_mediaplayer_proto_msgTypes,
	}.Build()
	File_mediaplayer_proto = out.File
	file_mediaplayer_proto_rawDesc = nil
	file_mediaplayer_proto_goTypes = nil
	file_mediaplayer_proto_depIdxs = nil
}
